### ISSUE TITLE
Latest version shopware-cli not available via brew

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/homebrew-tap#1]
### Actual behaviour

The latest version of shopware-cli (0.4.48) is not available via brew. I assume this is an automatic process which should be triggered?

### Expected behaviour

The latest version should be available: https://github.com/FriendsOfShopware/shopware-cli/releases/tag/0.4.48

### Steps to Reproduce?

/

**Comment by shyim** [comment]
Is fixed https://github.com/FriendsOfShopware/homebrew-tap/commit/01ab15135e4944964f090994cd43c894038d70ef

**Comment by wannevancamp** [comment]
homebrew is still not updating? Is there anything I can check or help with?
![image](https://github.com/user-attachments/assets/47a32d53-99c4-48c5-b3bf-cdc8527e2e06)

**Comment by shyim** [comment]
AHH it writes into wrong folder here

**Comment by wannevancamp** [comment]
Thanks! The latest version is now available through Homebrew 👍
